title: "Quantum Spintronics Laboratory (Q-LAB)"

description: "Advanced research in Spintronics, Altermagnetism, Quantum Materials and Condensed Matter Physics"

baseurl: "/quantum-spintronics-lab"

url: "https://brajbhusan-singh.github.io"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Dr. Braj Bhusan Singh"
  email: "brajbhusan.s@hbtu.ac.in"

permalink: pretty

timezone: Asia/Kolkata

